#!/bin/bash
OUT="INSTALADOR.sql"
{
  echo "-- ============================================================="
  echo "-- INSTALADOR SUPABASE — CEICS CUTLAJO (v3)"
  echo "-- Aplica TODAS las migraciones en orden."
  echo "-- Generado: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "--"
  echo "-- INSTRUCCIONES:"
  echo "-- 1. Si ya intentaste correr versión anterior y falló, primero ejecuta:"
  echo "--    drop schema public cascade;"
  echo "--    create schema public;"
  echo "--    grant all on schema public to public;"
  echo "--    grant all on schema public to anon, authenticated, service_role;"
  echo "-- 2. Pega TODO este archivo en SQL Editor de Supabase"
  echo "-- 3. Click Run (Cmd/Ctrl+Enter)"
  echo "-- ============================================================="
  echo ""
  for f in migrations/001_enums.sql migrations/002_identidad.sql migrations/003_catalogos.sql migrations/004_checklist.sql migrations/005_checklist_seed.sql migrations/006_protocolos.sql migrations/007_evaluacion.sql migrations/008_actas.sql migrations/009_triggers.sql migrations/010_rls.sql migrations/011_vistas_funciones.sql migrations/012_seed_comite.sql migrations/013_grants.sql; do
    echo ""
    echo "-- ============================================================="
    echo "-- $f"
    echo "-- ============================================================="
    cat "$f"
    echo ""
  done
  echo ""
  echo "-- ============================================================="
  echo "-- ✅ INSTALACIÓN COMPLETA"
  echo "-- ============================================================="
} > "$OUT"
echo "Regenerado: $OUT"
ls -lh "$OUT"
wc -l "$OUT"
